# NAME: Brendan Rossmango
# EMAIL: brendan0913@ucla.edu
# ID: 505370692     

default:
	gcc -Wall -Wextra lab1a.c -o lab1a

clean:
	rm -f lab1a *.tar.gz

dist: default
	tar -czvf lab1a-505370692.tar.gz lab1a.c Makefile README 

