# NAME: Brendan Rossmango
# EMAIL: brendan0913@ucla.edu
# ID: 505370692

default:
	gcc -Wall -Wextra lab3a.c -o lab3a

clean:
	rm -f lab3a *.gz

dist: default
	tar -czvf lab3a-505370692.tar.gz Makefile README lab3a.c ext2_fs.h
